# Generated by Django 3.0.6 on 2020-12-18 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_auto_20201218_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Answer',
        ),
    ]
